export interface UpdateItem {
  "Asset_ID": string,
  "Category": string,
  "Description": string,
  "SKU": string,
  "UOM": string,
  "BatchNo": string,
  "Asset_No": string,
  "Ref_No": string,
  "EPC_ID": string,
  "Date_of_Purchase": string,
  "Asset_Status_ID": string,
  "AssetStatus": string,
  //"Date_of_Scrap": string,
  "Cost": string,
  "Asset_Location_ID": string,
  "AssetLocation": string,
  "Date_of_Expire": string,
  "Warranty_Expiry_Date": string,
  "Calibration_Date": string,
  "Remarks": string,
  "Remarks2": string,
  "Remarks3": string,
  "Remarks4": string,
  "Remarks5": string,
  "Remarks6": string,
}